### ISSUE TITLE
Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.

### ISSUE THREAD

**Issue by VTSTech** [SmartRefer/crowdsale-factory#1]
https://github.com/SmartRefer/crowdsale-factory/blob/fea81ee503d1bb168741238fe23ccc9694c5f38e/contracts/tokens/basic-token.sol#L15

For reference this is the exact script I'm using. https://pastebin.com/vjuWGtNE
Line 150 in the pastebin.

I'm quite new to ETH Smart Contracts, So it's possible I'm doing something obvious wrong.

This output is from Official ETH Client 0.9.30
--
Could not compile source code. 

 Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
        BalanceOf(addr, _balances[addr]);
        ^------------------------------^
,

**Comment by da-moon** [comment]
@Veritas83 
I will look into it.  I haven't used the official client so I am not really sure what the issue is. If i had to guess, I would say it's because you have an older version of Solidity installed. I am using 0.4.19, if I remember currectly, `view` modifier didn't exist in the older versions and that seems to be the issue that the compiler is showing. In this version(04.18) it just shows me a warning.
I have been using the latest version of truffle and solidity, try compiling the contract with those.
Also, you can use Remix IDE. It should also work with it.
